# frozen_string_literal: true

require "bundler/gem_tasks"
require "rb_sys/extensiontask"

task build: :compile

RbSys::ExtensionTask.new("rimage") do |ext|
  ext.lib_dir = "lib/rimage"
end

task default: :compile
